import type { Metadata } from "next";
import { Inter, Caveat } from "next/font/google"; // Caveat'ı ekledik
import "./globals.css";
import Nav from "@/components/hero/nav/Nav";
import Header from "@/components/hero/header/Header";
import Scene from "@/components/three/Scene";
import Footer from "@/components/footer/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
});

export const metadata: Metadata = {
  title: "Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${caveat.variable} font-sans antialiased overflow-x-hidden bg-black `}
      >
        <Nav />
        <Header />
        <Scene />
        {children}
        <Footer />
      </body>
    </html>
  );
}
